### ISSUE TITLE
Test suite failing

### ISSUE THREAD

**Issue by lukehobbs** [SerCeMan/firewalker#20]
I'd love to use this tool, but I'm running into issues left and right (mostly around header value matching) - are the unit tests passing on your end? I'm not very familiar with yarn projects, so maybe it's a misconfiguration in my local setup.

I cloned down the repo and get these results when running the test suite:

```
Test Suites: 1 failed, 1 total
Tests:       26 failed, 17 passed, 43 total
Snapshots:   0 total
Time:        35.312 s
Ran all test suites.
```

**Comment by SerCeMan** [comment]
Hey, @lukehobbs! I can't reproduce the issue. Can you check if maybe https://github.com/SerCeMan/firewalker/pull/19 fixes it for you?
